procesos:
  - nombre: "Sincronización de Cursos"
    sp_name: "PKG_ETL_STG_BLACKBOARD_CIB.P_LOAD_TCIB_BLACKBOARD_CURSO"
    vista_origen: "V_CURSOS_BLACKBOARD"
    tabla_destino: "TCIB_BLACKBOARD_CURSO"
    key: "COURSE_ID"
    
  - nombre: "Sincronización de Cursos x Nodo"
    sp_name: "PKG_ETL_STG_BLACKBOARD_CIB.P_LOAD_TCIB_BLACKBOARD_CURSOXNODO"
    vista_origen: "V_CURSOSXNODO_BLACKBOARD"
    tabla_destino: "TCIB_BLACKBOARD_CURSOXNODO"
    key: "EXTERNAL_ASSOCIATION_KEY"

  - nombre: "Sincronización de Jerarquía"
    sp_name: "PKG_ETL_STG_BLACKBOARD_CIB.P_LOAD_TCIB_BLACKBOARD_JERARQUIA"
    vista_origen: "V_JERARQUIA_BLACKBOARD"
    tabla_destino: "TCIB_BLACKBOARD_JERARQUIA"
    key: "EXTERNAL_NODE_KEY"

  - nombre: "Sincronización de Matrícula"
    sp_name: "PKG_ETL_STG_BLACKBOARD_CIB.P_LOAD_TCIB_BLACKBOARD_MATRICULA"
    vista_origen: "V_MATRICULA_BLACKBOARD"
    tabla_destino: "TCIB_BLACKBOARD_MATRICULA"
    key: "EXTERNAL_COURSE_KEY"

  - nombre: "Sincronización de Período"
    sp_name: "PKG_ETL_STG_BLACKBOARD_CIB.P_LOAD_TCIB_BLACKBOARD_PERIODO"
    vista_origen: "V_PERIODO_BLACKBOARD"
    tabla_destino: "TCIB_BLACKBOARD_PERIODO"
    key: "EXTERNAL_TERM_KEY"

  - nombre: "Sincronización de Roles Secundarios"
    sp_name: "PKG_ETL_STG_BLACKBOARD_CIB.P_LOAD_TCIB_BLACKBOARD_ROLESSECUNDARIOS"
    vista_origen: "V_ROLSECUNDARIO_BLACKBOARD"
    tabla_destino: "TCIB_BLACKBOARD_ROLESSECUNDARIOS"
    key: "EXTERNAL_PERSON_KEY"
  
  - nombre: "Sincronización de Usuarios"
    sp_name: "PKG_ETL_STG_BLACKBOARD_CIB.P_LOAD_TCIB_BLACKBOARD_USUARIO"
    vista_origen: "V_USUARIOS_BLACKBOARD"
    tabla_destino: "TCIB_BLACKBOARD_USUARIO"
    key: "EXTERNAL_PERSON_KEY"

  - nombre: "Sincronización de Usuarios x Nodo"
    sp_name: "PKG_ETL_STG_BLACKBOARD_CIB.P_LOAD_TCIB_BLACKBOARD_USUARIOXNODO"
    vista_origen: "V_USUARIOSXNODO_BLACKBOARD"
    tabla_destino: "TCIB_BLACKBOARD_USUARIOXNODO"
    key: "EXTERNAL_ASSOCIATION_KEY"